/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import document.SearchResult;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.net.URLEncoder;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import jdbc.DataConnection;
import object.Data;

/**
 *
 * @author user
 */
public class GetSiteData extends javax.swing.JFrame {

    /**
     * Creates new form GetSiteData
     */
    public GetSiteData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yahooKey = new javax.swing.JTextField();
        getYahooData = new javax.swing.JButton();
        yahooKeywordLable = new javax.swing.JLabel();
        yahooLable = new javax.swing.JLabel();
        amazonKeywordLable = new javax.swing.JLabel();
        amazonKey = new javax.swing.JTextField();
        getAmazonData = new javax.swing.JButton();
        rakutenKeywordLable = new javax.swing.JLabel();
        rakutenKey = new javax.swing.JTextField();
        getRakutenData = new javax.swing.JButton();
        rakutenLabel = new javax.swing.JLabel();
        amazonLabel = new javax.swing.JLabel();
        showMessage = new javax.swing.JLabel();
        returnShowData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        yahooKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yahooKeyActionPerformed(evt);
            }
        });

        getYahooData.setText("商品情報を取得");
        getYahooData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getYahooDataActionPerformed(evt);
            }
        });

        yahooKeywordLable.setText("キーワード");

        yahooLable.setText("Yahooショッピング");

        amazonKeywordLable.setText("キーワード");

        amazonKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amazonKeyActionPerformed(evt);
            }
        });

        getAmazonData.setText("商品情報を取得");
        getAmazonData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAmazonDataActionPerformed(evt);
            }
        });

        rakutenKeywordLable.setText("キーワード");

        rakutenKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rakutenKeyActionPerformed(evt);
            }
        });

        getRakutenData.setText("商品情報を取得");
        getRakutenData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getRakutenDataActionPerformed(evt);
            }
        });

        rakutenLabel.setText("楽天");

        amazonLabel.setText("アマゾン");

        returnShowData.setText("商品管理");
        returnShowData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnShowDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(amazonKeywordLable, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rakutenKey, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(getRakutenData))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(amazonKey, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(getAmazonData)))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(showMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(returnShowData))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rakutenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amazonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yahooLable, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rakutenKeywordLable, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(yahooKeywordLable, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(yahooKey, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(getYahooData)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(yahooLable, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yahooKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getYahooData)
                    .addComponent(yahooKeywordLable))
                .addGap(25, 25, 25)
                .addComponent(amazonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amazonKeywordLable)
                    .addComponent(amazonKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getAmazonData))
                .addGap(35, 35, 35)
                .addComponent(rakutenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rakutenKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rakutenKeywordLable)
                    .addComponent(getRakutenData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnShowData))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yahooKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yahooKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yahooKeyActionPerformed

    private void amazonKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amazonKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amazonKeyActionPerformed

    private void getYahooDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getYahooDataActionPerformed
        try {
            // 時間のフォーマットを設定
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss ");
            String date = simpleDateFormat.format(new Date());
            // データを保存するためのlist
            ArrayList<Data> datas = new ArrayList<>();
            ArrayList<Data> subDatas = new ArrayList<>();
            SearchResult sr = new SearchResult();
            String key = URLEncoder.encode(yahooKey.getText(), "UTF-8");
            // サイトのアドレスを編集する,最初の5ページのデータを取得する
            for (int x = 0; x < 13; x += 3) {
                String url = "https://shopping.yahoo.co.jp/search?p=" + key + "&b=" + x + "1";
                datas = sr.searchYahoo(url);
                datas.remove(0);
                subDatas.addAll(datas);
            }
            System.out.println("取得したデータは" + subDatas.size() + "件です");
            // 重複したデータをlistから削除
            for (int x = 0; x < subDatas.size(); x++) {
                for (int y = 0; y < subDatas.size(); y++) {
                    if (x == y) {
                        continue;
                    }
                    if (subDatas.get(x).getImg().equals(subDatas.get(y).getImg()) && subDatas.get(x).getPrice() == subDatas.get(y).getPrice() && subDatas.get(x).getTitle().equals(subDatas.get(y).getTitle())) {
                        subDatas.remove(y);
                    } else {

                    }
                }
            }
            System.out.println("重複処理した数は" + subDatas.size());
            // データベースと連結する
            DataConnection c = new DataConnection();
            key = URLDecoder.decode(key, "UTF-8");
            String query_getSame = "select * from yahooSearchResultNow where keys = '" + key + "'";
            if (c.getSameData(query_getSame) == 1) {
                showMessage.setText(yahooKey.getText() + "があるため更新しました");
                // 旧データをyahooSearchResultに入れる
                String query_insertOldData = "insert into yahooSearchResult(select*from yahooSearchResultNow where keys='" + key + "')";
                //　更新時間を入れる
                String query_update = "update yahooSearchResult set updateTime='" + date + "' where keys='" + key + "'";
                // 旧データをyahooSearchResultNowから削除
                String query_delete = "delete from yahooSearchResultNow where keys='" + key + "'";
                c.excuteSQLQuery(query_insertOldData);
                c.excuteSQLQuery(query_update);
                c.excuteSQLQuery(query_delete);
                // 今回のデータをデータベースに入れる
                for (Data data : subDatas) {
                    String query = "insert into yahooSearchResultNow(id,keys,img,title,price,createTime)values(nextval('yahooSearchResultNow_id_seq'),'" + key + "','" + data.getImg() + "','"
                            + data.getTitle() + "','" + data.getPrice() + "','" + date + "');";
                    c.excuteSQLQuery(query);
                }
            } else {
                showMessage.setText(yahooKey.getText() + "のデータを取得しました");
                // データをそのまま入れる
                for (Data data : subDatas) {
                    String query = "insert into yahooSearchResultNow(id,keys,img,title,price,createTime)values(nextval('yahooSearchResultNow_id_seq'),'" + key + "','" + data.getImg() + "','"
                            + data.getTitle() + "','" + data.getPrice() + "','" + date + "');";
                    c.excuteSQLQuery(query);
                }
            }
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(GetSiteData.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GetSiteData.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_getYahooDataActionPerformed

    private void getAmazonDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAmazonDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getAmazonDataActionPerformed

    private void rakutenKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rakutenKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rakutenKeyActionPerformed

    private void getRakutenDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getRakutenDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getRakutenDataActionPerformed

    private void returnShowDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnShowDataActionPerformed

        ShowData sd = new ShowData();
        sd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnShowDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetSiteData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetSiteData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amazonKey;
    private javax.swing.JLabel amazonKeywordLable;
    private javax.swing.JLabel amazonLabel;
    private javax.swing.JButton getAmazonData;
    private javax.swing.JButton getRakutenData;
    private javax.swing.JButton getYahooData;
    private javax.swing.JTextField rakutenKey;
    private javax.swing.JLabel rakutenKeywordLable;
    private javax.swing.JLabel rakutenLabel;
    private javax.swing.JButton returnShowData;
    private javax.swing.JLabel showMessage;
    private javax.swing.JTextField yahooKey;
    private javax.swing.JLabel yahooKeywordLable;
    private javax.swing.JLabel yahooLable;
    // End of variables declaration//GEN-END:variables
}
